apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.dug.crawl.job_name }}
spec:
  schedule: {{ .Values.dug.crawl.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: set-vm-max-map-count
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sysctl', '-w', 'vm.max_map_count=262144']
            securityContext:
              privileged: true
          containers:
          - name: {{ .Values.dug.crawl.job_name }}-container
            image: {{ .Values.dug.web.image }}:{{ .Values.dug.web.image_tag }}
            env:
              - name: ELASTIC_API_HOST
                value: {{ .Values.dug.elasticsearch.service_name }}
              - name: ELASTIC_API_PORT
                value: {{ .Values.dug.elasticsearch.rest_port | quote }}
              - name: ELASTIC_USER
                value: {{ .Values.dug.elasticsearch.db_user }}
              - name: ELASTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: {{ .Values.dug.secrets.name }}
                    key: ELASTIC_PASSWORD
          restartPolicy: OnFailure
