apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dug.secrets.name }}
data:
  ELASTIC_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  NEO4J_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  REDIS_PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
