version: '3.0'

#################################################################################
##
## A service stack for HeLx semantic search.
##
#################################################################################
services:

  #################################################################################
  ##
  ## The OpenAPI endpoint for search. This is the only service to be
  ## exposed beyond the internal network.
  ##
  #################################################################################
  api:
    image: heliumdatastage/dug:latest
    networks:
      - dug-network
    environment:
      - ELASTIC_API_HOST=$ELASTIC_API_HOST
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
    entrypoint: [ "python", "-m", "dug.api", "--debug" ]
    # gunicorn --workers=2 --name=dug --bind=0.0.0.0 --timeout=100 dug.api:app
    volumes:
      - $PWD:/home/dug/dug
    ports:
      - 5551:5551 

  #################################################################################
  ##
  ## A search engine providing scalable indexing and full text search.
  ##
  #################################################################################
  elasticsearch:
    image: 'bitnami/elasticsearch:7.6.1'
    networks:
      - dug-network
    environment:
      - ELASTIC_PASSWORD=$ELASTIC_PASSWORD
      - discovery.type=single-node
    volumes:
      - $ELASTIC_DATA:/bitnami/elasticsearch/data
    ports:
      - '9200:9200'
      - '9300:9300'

  #################################################################################
  ##
  ## A graph database provides query over linked data to drive indexing.
  ##
  #################################################################################
  neo4j:
    image: bitnami/neo4j:3.5.14
    networks:
      - dug-network
    environment:
      - NEO4J_PASSWORD=$NEO4J_PASSWORD
      - NEO4J_HOST=$HOSTNAME
    volumes:
      - $NEO4J_DATA:/bitnami
    ports:
      - '7474:7474'
      - '7473:7473'
      - '7687:7687'
          
  #################################################################################
  ##
  ## A memory cache for results of high volume service requests.
  ##
  #################################################################################
  redis:
    image: 'bitnami/redis:5.0.8'
    networks:
      - dug-network
    environment:
      - REDIS_PASSWORD=$REDIS_PASSWORD
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - $REDIS_DATA:/bitnami/redis/data
    ports:
      - '6379:6379'
      
networks:
  dug-network:
    driver: bridge

