apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: search
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: search
            image: heliumdatastage/search:latest
          restartPolicy: OnFailure