apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: search
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: set-vm-max-map-count
            image: busybox
            imagePullPolicy: IfNotPresent
            command: ['sysctl', '-w', 'vm.max_map_count=262144']
            securityContext:
              privileged: true
          containers:
          - name: search
            image: heliumdatastage/dug:latest
            env:
              - name: "ELASTIC_API_HOST"
                value: "elasticsearch"
              - name: "ELASTIC_API_PORT"
                value: "9200"
              - name: "ELASTIC_USER"
                valueFrom:
                  configMapKeyRef:
                    name: dug-configmap
                    key: "ELASTIC_USER"
              - name: "ELASTIC_PASSWORD"
                valueFrom:
                  secretKeyRef:
                    name: dug-secrets
                    key: "ELASTIC_PASSWORD"
          restartPolicy: OnFailure
