dug:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch
    image_tag: 7.9.1
    app_name: elasticsearch
    pvc_name: dug-elasticsearch-pvc
    service_name: elasticsearch
    statefulset_name: dug-elasticsearch
    initial_master_name: dug-elasticsearch-0
    rest_port: 9200
    nodes_com_port: 9300
    storage_size: 5Gi
    storage_class: dug-storage
    db_user: elastic
    init_config_name: elasticsearch-initcontainer
    xmx: 2g
    xms: 2g
    cluster_name: dug-elasticsearch-cluster
    roles:
      master: "true"
      ingest: "true"
      data: "true"
    replica_count: 3
    liveness:
      initial_delay: 30
      check_interval: 10
  neo4j:
    image: bitnami/neo4j
    image_tag: 3.5.14
    app_name: neo4j
    pvc_name: dug-neo4j-pvc
    service_name: neo4j
    deployment_name: neo4j
    http_port: 7474
    https_port: 7473
    bolt_port: 7687
    storage_size: 1G
    db_user: neo4j
  redis:
    image: bitnami/redis
    image_tag: 5.0.8
    app_name: redis
    pvc_name: dug-redis-pvc
    service_name: redis
    deployment_name: redis
    storage_size: 5G
    redis_port: 6389
  web:
    image: heliumdatastage/dug
    image_tag: develop-v0.0.25
    app_name: dug
    service_name: dug
    deployment_name: dug
    api_port: 5551
    debug: false
    ambassador:
      search:
        map_name: dug-search
        prefix: /search
      search_kg:
        map_name: dug-search-kg
        prefix: /search_kg
  secrets:
    name: dug-secrets
  crawl:
    job_name: search
    schedule: "*/1 * * * *"
  search_client:
    app_name: dug-search-client
    deployment_name: dug-search-client
    service_name: dug-search-client
    http_port: 80
    container_port: 8080
    image: heliumdatastage/dug-search-client
    image_tag: 5d443f9-dev
    ambassador:
      ui:
        map_name: dug-ui
        prefix: /ui
  nboost:
    app_name: dug-nboost
    deployment_name: dug-nboost
    service_name: dug-nboost
    image: koursaros/nboost
    image_tag: 0.3.9-pt
    api_port: 8000

  # create_pvcs: true
